name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
  full-test:
    runs-on: self-hosted # باید runner خودتون رو تنظیم کرده باشید
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
          submodules: 'recursive'
      
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Run build
        timeout-minutes: 600
        run: |
          # حذف دستورات Docker و اجرای مستقیم
          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
          cd ${GITHUB_WORKSPACE}
          ./build.sh

      - name: Cleanup
        if: always()
        run: |
          ssh-add -D

      - name: Run full test
        timeout-minutes: 15
        run: |
          cd ${GITHUB_WORKSPACE}
          ./full-test.sh