name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
  full-test:
    runs-on: self-hosted  # باید runner روی سیستم شما تنظیم شده باشد
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: 'recursive'

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Run full test
        timeout-minutes: 15
        run: |
          # تغییر مسیر به دایرکتوری پروژه
          cd /home/pooria/colorado/assignment-6-yocto

          # اجرای اسکریپت تست
          ./full-test.sh

      - name: Cleanup
        if: always()
        run: |
          ssh-add -D